MVC/Controllers/RentMovieController.cs
using ApplicationService.DTOs;
using MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class RentMovieController : Controller
    {
        // GET: RentMovie
        public ActionResult Index(string SearchUM="")
        {
            List<UserMovieVM> userMoviesVMs = new List<UserMovieVM>();
            using(SOAPService.Service1Client service = new SOAPService.Service1Client())
            {
                foreach(var item in service.GetUserMovies(SearchUM))
                {
                    userMoviesVMs.Add(new UserMovieVM(item));
                }
            }
            return View(userMoviesVMs);
        }


        public ActionResult Details(int id)
        {
            UserMovieVM userMovieVM = new UserMovieVM();
            using (SOAPService.Service1Client service = new SOAPService.Service1Client())
            {
                var userMovieDto = service.GetUserMovieById(id);
                userMovieVM = new UserMovieVM(userMovieDto);
            }
            return View(userMovieVM);
        }

        public ActionResult Create()
        {
            ViewBag.Movies = Helpers.LoadDataUtilities.LoadMovieDataList();
            ViewBag.Users = Helpers.LoadDataUtilities.LoadUserDataList();

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserMovieVM userMovieVM)
        {
            try
            {
                using (SOAPService.Service1Client service = new SOAPService.Service1Client())
                {
                    UserMovieDTO userMovieDTO = new UserMovieDTO
                    {

                        Rent_Day = userMovieVM.Rent_Day,
                        Return_Day = userMovieVM.Return_Day,
                        Comment = userMovieVM.Comment,
                        Price = userMovieVM.Price,
                        Movie_Id=userMovieVM.Movie_Id,
                        Movie = new MovieDTO
                        {
                            Movie_Id = userMovieVM.Movie_Id,
                        },
                        User_Id=userMovieVM.User_Id,
                        User = new UserDTO
                        {
                            User_Id=userMovieVM.User_Id,
                        }
                    };
                    service.PostUserMovie(userMovieDTO);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Movies = Helpers.LoadDataUtilities.LoadMovieDataList();
                ViewBag.Users = Helpers.LoadDataUtilities.LoadUserDataList();

                return View();
            }
            
        }

        public ActionResult Edit(int id)
        {
            UserMovieVM userMovieVM = new UserMovieVM();
            using (SOAPService.Service1Client service = new SOAPService.Service1Client())
            {
                var userMovieDto = service.GetUserMovieById(id);
                userMovieVM = new UserMovieVM(userMovieDto);
            }
            ViewBag.Movies = Helpers.LoadDataUtilities.LoadMovieDataList();
            ViewBag.Users = Helpers.LoadDataUtilities.LoadUserDataList();
            return View(userMovieVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserMovieVM userMovieVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SOAPService.Service1Client service = new SOAPService.Service1Client())
                    {
                        UserMovieDTO userMovieDTO = new UserMovieDTO
                        {
                            UserMovie_Id=userMovieVM.UserMovie_Id,
                            Rent_Day = userMovieVM.Rent_Day,
                            Return_Day = userMovieVM.Return_Day,
                            Comment = userMovieVM.Comment,
                            Price = userMovieVM.Price,
                            Movie_Id = userMovieVM.Movie_Id,
                            Movie = new MovieDTO
                            {
                                Movie_Id = userMovieVM.Movie_Id,
                            },
                            User_Id = userMovieVM.User_Id,
                            User = new UserDTO
                            {
                                User_Id = userMovieVM.User_Id,
                            }

                        };
                        service.PutUserMovie(userMovieDTO);
                    }

                    return RedirectToAction("Index");
                }

                ViewBag.Movies = Helpers.LoadDataUtilities.LoadMovieDataList();
                ViewBag.Users = Helpers.LoadDataUtilities.LoadUserDataList();
                return View();
            }
            catch
            {
                ViewBag.Movies = Helpers.LoadDataUtilities.LoadMovieDataList();
                ViewBag.Users = Helpers.LoadDataUtilities.LoadUserDataList();
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            using (SOAPService.Service1Client service = new SOAPService.Service1Client())
            {
                service.DeleteUserMovie(id);
            }
            return RedirectToAction("Index");
        }

    }
}

MVC/Views/RentMovie/Create.cshtml
@model MVC.ViewModels.UserMovieVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserMovieVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.UserMovie_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserMovie_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserMovie_Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Movie_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @* @Html.EditorFor(model => model.Movie_Id, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("Movie_Id",ViewBag.Movies as IEnumerable<SelectListItem>, new { @class = "form-control"})

                @Html.ValidationMessageFor(model => model.Movie_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.User_Id, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("User_Id", ViewBag.Users as IEnumerable<SelectListItem>, new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rent_Day, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rent_Day, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rent_Day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Return_Day, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Return_Day, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Return_Day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Views/RentMovie/Delete.cshtml
@model MVC.ViewModels.UserMovieVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserMovieVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserMovie_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserMovie_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movie_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rent_Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rent_Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Return_Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Return_Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC/Views/RentMovie/Details.cshtml
@model MVC.ViewModels.UserMovieVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserMovieVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserMovie_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserMovie_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movie_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rent_Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rent_Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Return_Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Return_Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.UserMovie_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC/Views/RentMovie/Edit.cshtml
@model MVC.ViewModels.UserMovieVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>UserMovieVM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @*<div class="form-group">
            @Html.LabelFor(model => model.UserMovie_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserMovie_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserMovie_Id, "", new { @class = "text-danger" })
            </div>
        </div>*@
    @Html.HiddenFor(model => model.UserMovie_Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Movie_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Movie_Id", ViewBag.Movies as IEnumerable<SelectListItem>, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Movie_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.User_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("User_Id", ViewBag.Users as IEnumerable<SelectListItem>, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.User_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Rent_Day, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Rent_Day, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Rent_Day, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Return_Day, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Return_Day, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Return_Day, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Views/RentMovie/Index.cshtml
@model IEnumerable<MVC.ViewModels.UserMovieVM>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "RentMovie"))
{
    <p>
        Search Name: @Html.TextBox("SearchUM", ViewBag.FilterValue as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserMovie_Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Movie_Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User_Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rent_Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Return_Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserMovie_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User_Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rent_Day)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Return_Day)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UserMovie_Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.UserMovie_Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UserMovie_Id })
            </td>
        </tr>
    }

</table>